# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: genomespace_new_development
  host: gsrecipetest.c0vdttbk18cp.us-east-1.rds.amazonaws.com
  pool: 5
  username: gsdbadmin
  password: gsdbpassword
  socket: /tmp/mysql.sock

#  pool: 5
#  username: root
#  password:
#  socket: /tmp/mysql.sock

rds_test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: genomespace_new_development
  host: gsrecipetest.c0vdttbk18cp.us-east-1.rds.amazonaws.com
  pool: 5
  username: gsdbadmin
  password: gsdbpassword
  socket: /tmp/mysql.sock

# rds is the new production on AWS now
rds:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: genomespace_production
  host: gsrecipetest.c0vdttbk18cp.us-east-1.rds.amazonaws.com
  pool: 5
  username: gsdbadmin
  password: gsdbpassword
  socket: /tmp/mysql.sock


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: genomespace_new_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: mysql-prd1.broadinstitute.org
  database: genomespace_production
  pool: 5
  username: genomespace
  password: g3n0m3sp4c3
  socket: /tmp/mysql.sock

prod4000:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: mysql-prd1.broadinstitute.org
  database: genomespace_prod4000
  pool: 5
  username: genomespace
  password: g3n0m3sp4c3
  socket: /tmp/mysql.sock
