#! /usr/bin/env ruby

require 'net/smtp'

RAILS_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))
Dir.chdir(RAILS_ROOT)

# get command line arguments for environment and number of workers
@env = ARGV[0].nil? ? "production" : ARGV[0]

@from_email = "no-reply@genomespace.org"
@to_email = "bistline@broadinstitute.org"

# get current delayed_job status messages
dj_status = `script/delayed_job status #{@env}`

# checks to see if any workers have been killed
@date = Time.now.strftime("%Y-%m-%d %H:%M:%S")
if dj_status.include?("killed") || dj_status.include?("no instances running")
	@log_message =  "#{@date}: One or more delayed_job workers have died.  Restarting daemon with #{@num_workers} workers.\n"

	# restart delayed job workers and update log message
	system("script/delayed_job restart #{@env}")
	sleep(30)
	new_status = `script/delayed_job status #{@env}`
	new_time = Time.now.strftime("%Y-%m-%d %H:%M:%S")
	new_status.split("\n").each {|status| @log_message << "#{new_time}: #{status}\n"}

	# send email to admin
	Net::SMTP.start('smtp.broadinstitute.org', 25) do |smtp|
		smtp.open_message_stream(@from_email, @to_email) do |contents|
			contents.puts "From: #{@from_email}"
			contents.puts "To: #{@to_email}"
			contents.puts "Content-Type: text/html; charset=utf-8"
			contents.puts "Subject: GenomeSpace Website DelayedJob worker died as of #{@date}"
			contents.puts ""
			contents.puts "#{@log_message.gsub(/\n/, '<br />')}"
		end
	end
else
	@log_message = "#{@date}: All workers running normally.\n"
end

# write message to log file
logfile = File.open(File.join(RAILS_ROOT,'log/job_monitor.log'),'a')
logfile.write @log_message
logfile.close
